# ==================================================================
# module list
# ------------------------------------------------------------------
# flashlight       master     (git, CUDA backend)
# ==================================================================

FROM flml/flashlight:cuda-base-consolidation-latest

# just in case for visibility
ENV MKLROOT="/opt/intel/mkl"

# ==================================================================
# flashlight with CUDA backend
# ------------------------------------------------------------------
# Setup and build flashlight
RUN mkdir /root/flashlight

COPY . /root/flashlight

RUN cd /root/flashlight && mkdir -p build && \
    cd build && cmake .. -DCMAKE_BUILD_TYPE=Release \
                         -DCMAKE_INSTALL_PREFIX=/opt/flashlight \
                         -DFL_BACKEND=CUDA \
                         -DFL_BUILD_LIB_COMMON=ON \
                         -DFL_BUILD_CORE=ON \
                         -DFL_BUILD_PKG_TEXT=ON \
                         -DFL_BUILD_PKG_RUNTIME=ON \
                         -DFL_BUILD_LIB_SEQUENCE=ON \
                         -DFL_BUILD_LIB_TEXT=ON \
                         -DFL_BUILD_LIB_AUDIO=ON \
                         -DFL_BUILD_PKG_SPEECH=ON \
                         -DFL_BUILD_APP_ASR=ON \
                         -DFL_BUILD_APP_LM=ON \
                         -DFL_BUILD_APP_ASR_TOOLS=ON \
                         -DFL_BUILD_ALL_APPS=OFF && \
    make install -j$(nproc)